

POST http://localhost:7788/v1/did/web
Content-Type: application/json
   
{
  "domainName": "cerroancon-6",
  "pub": "SCqcujhpdXvHhVo3FfLHc5nToKiLc5yukj5MqSgLSbU3cZmwtoko2qSNizphk4wAZvvcSV3htWYy3tvnPiBacpki"
}

