

POST https://ancon.did.pa/api/v0/dagjson
Content-Type: application/json

{
  "path": "/",
  "data": {
    "name": "react metadata sample",
    "owner": "juan",
    "description": "juan testing sample",
    "image": "https://explore.ipld.io/#/explore/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D"
  }
}