

POST http://localhost:7788/v0/dagjson
Content-Type: application/json

{
  "path": "/",
  "data": {
    "name": "bee swarm metadata sample",
    "owner": "juan",
    "description": "swarm testing sample",
    "image": "helloworld.jpg"
  }
}