

POST http://localhost:7788/dagjson
Content-Type: application/json

{
  "path": "/",
  "data": {
    "name": "XDV metadata sample",
    "description": "testing sample",
    "image": "https://explore.ipld.io/#/explore/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D"
  }
}